#!/usr/bin/env python3
"""
fix-methodology.py — state the two listing tests as two tests.

Wave 3 went up while the page read as one strong rule (convergence of destination)
followed by a large exception. That ordering is the weak point: the site's best argument
appeared not to cover its biggest wave, and the fallback read close to the shape test a
critic had already objected to publicly. Same facts, restated as two tests of equal
standing, with the marks that were being left unsaid.

The three additions for Wave 3, each checked rather than asserted:
  firmware epoch  the oldest input coin across the 215 published sweeps is block 677,217,
                  about two weeks after the vulnerable firmware shipped at 674,951. The
                  detector does test this, and in the fee band it rejected nothing, so it
                  is an observation about the population and not an artefact of filtering.
  still unspent   all 214 vaults, re-confirmed by wave3-refresh.py
  outside total   Galaxy reported a wave of this size in this window

usage: fix-methodology.py [--dry-run] [--no-deploy]
"""
import os
import re
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import publish

MEth = os.path.join(publish.PUBLIC, "methodology.html")

OLD_START = "    No single mark settles it on its own."
END_MARK = "<h2>What each cluster rests on"

NEW = """    No single mark settles it on its own. An owner rescuing coins one UTXO per transaction, to keep
    their histories separate, produces the same shape the tool does. What an owner cannot produce is
    <strong>convergence</strong> with hundreds of strangers, and there are two kinds of it in this
    incident. An address is listed on this site only when its sweep shows one of them, and never on
    shape alone.
  </p>
  <p>
    <strong>Convergence of destination.</strong> Hundreds of sweeps land inside one window, every one
    paying the same fee rate regardless of what the network was charging, and every one paying into
    the same address. A rescue goes to the owner's own wallet, and a thousand separate owners cannot
    share one destination. The first, second and fifth clusters are listed on this test.
  </p>
  <p>
    <strong>Convergence of fee.</strong> Wave 3 removed the shared destination deliberately, giving
    each drained wallet its own fresh address and then its own fresh P2WSH vault, 214 of them sharing
    nothing, which is why this site missed the wave for two days. What it did not remove is the fee.
    Its 215 sweeps all paid within a hair of 201 sat/vB while the network was charging under 3, and a
    rate that constant across transactions sharing no address is a number hardcoded in a script rather
    than 215 strangers independently choosing the same urgent fee. Sixteen further chains matched the
    shape but paid scattered rates, and they were left off rather than published on shape alone.
  </p>
  <p>
    Three further marks hold across that wave, and are set out here because the fee should not carry
    it alone. The oldest coin anywhere in the set was created in block 677,217, about two weeks after
    the vulnerable firmware shipped: nothing in the set predates the flaw, which is what a population
    of addresses generated by that firmware would look like. All 214 vaults are still unspent, where
    an owner who moves coins to safety goes on to use the wallet they moved to. And Galaxy Research
    reported a wave of this size in this window from their own separate analysis, which is harder to
    account for if these sweeps were owners rescuing their own coins.
  </p>
"""


def main():
    dry = "--dry-run" in sys.argv
    if publish.conflict_guard():
        raise SystemExit("syncthing conflict copies present, refusing")
    if publish.self_check(verbose=False):
        raise SystemExit("site invariants broken before edit; aborting")

    s = open(MEth, encoding="utf-8").read()
    i = s.find(OLD_START)
    if i < 0:
        raise SystemExit("could not find the 'No single mark' paragraph; the page changed "
                         "again, re-read it before editing")
    j = s.find(END_MARK, i)
    if j < 0:
        raise SystemExit("could not find the cluster table heading")
    # keep whatever whitespace/closing markup sits between the last </p> and the <h2>
    tail_start = s.rfind("</p>", i, j)
    if tail_start < 0:
        raise SystemExit("could not find the closing </p>")
    out = s[:i] + NEW + s[tail_start + len("</p>"):]

    for must in ("Convergence of destination", "Convergence of fee", "677,217",
                 "still unspent", "reported a wave of this size in this window"):
        if must not in out:
            raise SystemExit(f"rewrite lost {must!r}")
    if out.count("<h2>What each cluster rests on") != 1:
        raise SystemExit("cluster table heading duplicated or lost")

    if dry:
        print("dry run; would rewrite methodology.html")
        print(f"  replacing {j - i} chars with {len(NEW)}")
        return 0

    bak = MEth + ".fmbak"
    shutil.copy2(MEth, bak)
    try:
        tmp = MEth + ".tmp"
        open(tmp, "w", encoding="utf-8").write(out)
        os.replace(tmp, MEth)
        probs = publish.self_check(verbose=True)
        if probs:
            raise RuntimeError(f"invariants broken: {probs}")
    except Exception:
        shutil.copy2(bak, MEth)
        raise
    finally:
        if os.path.exists(bak):
            os.remove(bak)

    print("methodology.html rewritten")
    if "--no-deploy" in sys.argv:
        return 0
    publish.deploy()
    print("deployed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
